# ========================= GLOBAL CONFIGURATION ==========================

# Market timings
MARKET_OPEN = (9, 15)           # 9:15 AM IST
MARKET_CLOSE = (15, 30)         # 3:30 PM IST
INTRADAY_SQUAREOFF = (14, 55)   # 2:55 PM exit

# WebSocket settings
WEBSOCKET_RECONNECT_DELAY = 5   # seconds delay for reconnection attempts
MAX_CANDLE_STORAGE = 5000       # number of aggregated candles to hold

# Benchmark for strategy comparison
BENCHMARK_SYMBOL = "NSE:NIFTY50-INDEX"

# File containing Fyers access token generated by Token Manager
ACCESS_TOKEN_FILE = "access.txt"

# Allowed timeframe resolutions for backtesting / candles
TIMEFRAME_RESOLUTIONS = ["1", "3", "5", "10", "15", "20", "30", "60", "120", "240", "D"]

# UI Color Codes
COLOR_GREEN = "#16a34a"
COLOR_RED = "#dc2626"
COLOR_BLUE = "#3b82f6"
COLOR_ORANGE = "#fb923c"
